# Generated by Django 2.2.10 on 2023-03-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_auto_20230226_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='resume',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='College'),
        ),
        migrations.AddField(
            model_name='resume',
            name='companies',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact'),
        ),
    ]
