# Generated by Django 2.2.10 on 2023-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0015_auto_20230330_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='score',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Score'),
        ),
    ]
