# Generated by Django 2.2 on 2023-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0018_resume_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Ideal Candidate Resume')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('companies', models.CharField(blank=True, max_length=255, null=True, verbose_name='Companies')),
                ('college', models.CharField(blank=True, max_length=255, null=True, verbose_name='College')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Summary')),
                ('experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Experience')),
                ('score', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Score')),
                ('score1', models.IntegerField(blank=True, null=True, verbose_name='Score1')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
            ],
        ),
    ]
