# Generated by Django 2.2.10 on 2023-02-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_auto_20191022_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='total_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Summary'),
        ),
    ]
