# Generated by Django 2.2.10 on 2023-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_auto_20230222_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Score'),
        ),
    ]
