# Generated by Django 2.2.10 on 2023-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_resume_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
