# Generated by Django 2.2.10 on 2023-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0016_auto_20230402_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score1'),
        ),
    ]
